### ISSUE TITLE
Feature - Download option for images and videos

### ISSUE THREAD

**Issue by mjsal** [SanjayDevTech/instautils#4]
it only shows the pic/video on the screen but never downloads it and there's no download option.

**Comment by SanjayDevTech** [comment]
Because of some storage confusions in new Android versions (I meant Scoped storage), I left the duty of downloading the image to the developer... 


instautils will provide you a Bitmap data, so u can play around with it...

I can take this issue as a Feature request and will soon working on it...


Thank u :)

**Comment by mjsal** [comment]
yeah I'm aware that Api 30 has different write permissions so I tried changing the sdk to an older version it still didn't work. also, does it work for video or just images?

**Comment by SanjayDevTech** [comment]
No I didn't implemented the feature yet...

May be I have to research on it for saving both image and video files

**Comment by SanjayDevTech** [comment]
Archiving this project
Please check #7 
Thank you
